use_frameworks!

platform :ios, '9.0'

target 'HSAFNetworking_Example' do
  pod 'HSAFNetworking', :path => '../'

  target 'HSAFNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
